-- - phpMyAdmin SQL Dump
-- version 2.11.4
-- http://www.phpmyadmin.net
--
-- Host: s156.eatj.com:3307
-- Generation Time: Sep 30, 2013 at 05:02 AM
-- Server version: 5.0.77
-- PHP Version: 5.2.9

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Database: `binaryedu`
--

-- --------------------------------------------------------

--
-- Table structure for table `test`
--

-- CREATE TABLE IF NOT EXISTS `betest` (
--   `id` bigint(20) NOT NULL auto_increment,
--   `NAME` varchar(255) default NULL,
--   `DATE` datetime default NULL,
--   `creationDate` datetime default NULL,
--   `available` bit(1) default NULL,
--   `numQuestions` int(11) default NULL,
--   `marks` int(11) default NULL,
--   `duration` bigint(20) default NULL,
--   `negative` float default NULL,
--   `instructions` longtext,
--   `type` varchar(255) NOT NULL,
--   PRIMARY KEY  (`id`)
-- ) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=43 ;

--
-- Dumping data for table `test`
--

INSERT INTO betest (id, NAME, creationDate, available, numQuestions, marks, duration, negative, instructions, TYPE) VALUES
(1, 'CAT Free Test 01', '2009-09-08 13:57:15', '1', 90, 90, 135, 0.25, '<ol><li>The total time for the test is 150 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Quantitative Ability, <b>Section II</b> - Verbal Ability & Reading Comprehension, and <b>Section III</b> - Data Interpretation & Logical Ability. Each section contains a total of 30 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT'),
(2, 'CAT Free Test 02', '2009-09-08 13:57:15', '1', 75, 75, 135, 0.25, '<ol><li>The total time for the test is 150 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Data Interpretation & Logical Ability, <b>Section II</b>- Verbal Ability & Reading Comprehension, and <b>Section III</b> - Quantitative Ability. Each section contains a total of 25 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT'),
(3, 'CAT Free Test 03', '2009-09-08 13:57:15', '1', 70, 70, 135, 0.25, '<ol><li>The total time for the test is 135 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Quantitative Ability (20 Questions), <b>Section II</b> - Data Interpretation (20 Questions), and <b>Section III</b> - Reading Comprehension & Verbal Ability (30 Questions). All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT'),
(4, 'CAT Free Test 04', '2009-09-08 13:57:15', '1', 70, 70, 135, 0.25, '<ol><li>The total time for the test is 135 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Quantitative Ability (20 Questions), <b>Section II</b> - Data Interpretation (20 Questions), and <b>Section III</b> - Reading Comprehension & Verbal Ability (30 Questions). All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT'),
(5, 'CAT Free Test 05', '2009-09-08 13:57:15', '1', 65, 65, 135, 0.25, '<ol><li>The total time for the test is 135 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Reading Comprehension & Verbal Ability (25 Questions), <b>Section II</b> - Quantitative Ability (20 Questions), and <b>Section III</b> - Data Interpretation (20 Questions). All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT'),
(6, 'Quick Quiz - Data Interpretation 01', '2009-09-14 18:41:57', '1', 5, 5, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 5 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(7, 'Quick Quiz - Data Interpretation 02', '2009-09-14 18:41:57', '1', 5, 5, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 5 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(8, 'Quick Quiz - Data Interpretation 03', '2009-09-14 18:41:57', '1', 4, 4, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 4 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(9, 'Quick Quiz - Data Interpretation 04', '2009-09-14 18:41:57', '1', 5, 5, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 5 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(10, 'Quick Quiz - Data Interpretation 05', '2009-09-14 18:41:57', '1', 5, 5, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 5 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(11, 'Quick Quiz - Quantitative Analysis 01', '2009-09-17 09:45:15', '1', 5, 5, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 5 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(12, 'Quick Quiz - Quantitative Analysis 02', '2009-09-17 09:45:15', '1', 5, 5, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 5 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(13, 'Quick Quiz - Quantitative Analysis 03', '2009-09-17 09:45:15', '1', 5, 5, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 5 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(14, 'Quick Quiz - Quantitative Analysis 04', '2009-09-17 09:45:15', '1', 5, 5, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 5 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(15, 'Quick Quiz - Quantitative Analysis 05', '2009-09-17 09:45:15', '1', 5, 5, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 5 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(16, 'Quick Quiz - Reading Comprehension 01', '2009-09-17 09:45:15', '1', 4, 4, 15, 0.25, '<ol><li>The total time for the test is 15 minutes.</li><li>The test contains a total of 4 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(17, 'Quick Quiz - Reading Comprehension 02', '2009-09-17 09:45:15', '1', 4, 4, 15, 0.25, '<ol><li>The total time for the test is 15 minutes.</li><li>The test contains a total of 4 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(18, 'Quick Quiz - Reading Comprehension 03', '2009-09-17 09:45:15', '1', 4, 4, 15, 0.25, '<ol><li>The total time for the test is 15 minutes.</li><li>The test contains a total of 4 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(19, 'Quick Quiz - Reading Comprehension 04', '2009-09-17 09:45:15', '1', 4, 4, 15, 0.25, '<ol><li>The total time for the test is 15 minutes.</li><li>The test contains a total of 4 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(20, 'Quick Quiz - Reading Comprehension 05', '2009-09-17 09:45:15', '1', 4, 4, 15, 0.25, '<ol><li>The total time for the test is 15 minutes.</li><li>The test contains a total of 4 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(21, 'Quick Quiz - Reading Comprehension 06', '2009-09-17 09:45:15', '1', 4, 4, 15, 0.25, '<ol><li>The total time for the test is 15 minutes.</li><li>The test contains a total of 4 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(22, 'Section Test - Data Interpretation 01', '2009-09-23 12:28:42', '1', 20, 20, 45, 0.25, '<ol><li>The total time for the test is 45 minutes.</li><li>The test contains a total of 20 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'ST'),
(23, 'Section Test - Data Interpretation 02', '2009-09-23 12:28:42', '1', 20, 20, 45, 0.25, '<ol><li>The total time for the test is 45 minutes.</li><li>The test contains a total of 20 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'ST'),
(24, 'Section Test - Data Interpretation 03', '2009-09-23 12:28:42', '1', 20, 20, 45, 0.25, '<ol><li>The total time for the test is 45 minutes.</li><li>The test contains a total of 20 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'ST'),
(25, 'Section Test - Quantitative Analysis 01', '2009-09-23 12:28:42', '1', 20, 20, 45, 0.25, '<ol><li>The total time for the test is 45 minutes.</li><li>The test contains a total of 20 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'ST'),
(26, 'Section Test - Quantitative Analysis 02', '2009-09-23 12:28:42', '1', 20, 20, 45, 0.25, '<ol><li>The total time for the test is 45 minutes.</li><li>The test contains a total of 20 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'ST'),
(27, 'Section Test - Quantitative Analysis 03', '2009-09-23 12:28:42', '1', 20, 20, 45, 0.25, '<ol><li>The total time for the test is 45 minutes.</li><li>The test contains a total of 20 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'ST'),
(28, 'Section Test - Reading Comprehension 01', '2009-09-23 12:28:42', '1', 20, 20, 45, 0.25, '<ol><li>The total time for the test is 45 minutes.</li><li>The test contains a total of 20 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'ST'),
(29, 'Section Test - Reading Comprehension 02', '2009-09-23 12:28:42', '1', 20, 20, 45, 0.25, '<ol><li>The total time for the test is 45 minutes.</li><li>The test contains a total of 20 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'ST'),
(30, 'Section Test - Reading Comprehension 03', '2009-09-23 13:37:59', '1', 20, 20, 45, 0.25, '<ol><li>The total time for the test is 45 minutes.</li><li>The test contains a total of 20 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'ST'),
(31, 'Quick Quiz - Vocabulary 01', '2009-09-23 12:28:42', '1', 10, 10, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 10 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(32, 'Quick Quiz - Vocabulary 02', '2009-09-23 13:37:59', '1', 10, 10, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 10 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(33, 'Quick Quiz - Vocabulary 03', '2009-09-23 13:37:59', '1', 10, 10, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 10 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(34, 'Quick Quiz - Vocabulary 04', '2009-09-23 13:37:59', '1', 10, 10, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 10 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(35, 'Quick Quiz - Vocabulary 05', '2009-09-23 13:37:59', '1', 10, 10, 10, 0.25, '<ol><li>The total time for the test is 10 minutes.</li><li>The test contains a total of 10 questions. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'QQ'),
(36, 'CAT Free Test 06', '2009-10-13 08:42:14', '1', 65, 65, 135, 0.25, '<ol><li>The total time for the test is 135 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Quantitative Ability (20 Questions), <b>Section II</b> - Data Interpretation (20 Questions), and <b>Section III</b> - Reading Comprehension & Verbal Ability (25 Questions). All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT'),
(37, 'CAT Free Test 07', '2009-10-13 08:42:14', '1', 70, 70, 135, 0.25, '<ol><li>The total time for the test is 135 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Quantitative Ability (20 Questions), <b>Section II</b> - Data Interpretation (20 Questions), and <b>Section III</b> - Reading Comprehension & Verbal Ability (30 Questions). All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT'),
(38, 'Free CAT Mock Test 1', '2009-10-30 01:33:55', '1', 68, 68, 135, 0.25, '<ol><li>The total time for the test is 135 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Quantitative Ability, <b>Section II</b> - Data Interpretation & Logical Ability, and <b>Section III</b> - Verbal Ability & Reading Comprehension. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT'),
(39, 'Free CAT Mock Test 2', '2009-11-05 19:41:26', '1', 67, 67, 135, 0.25, '<ol><li>The total time for the test is 135 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Quantitative Ability, <b>Section II</b> - Data Interpretation & Logical Ability, and <b>Section III</b> - Verbal Ability & Reading Comprehension. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT'),
(40, 'Free CAT Mock Test 3', '2009-11-13 09:37:13', '1', 71, 71, 135, 0.25, '<ol><li>The total time for the test is 135 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Verbal Ability & Reading Comprehension, <b>Section II</b> - Quantitative Ability, and <b>Section III</b> - Data Interpretation & Logical Ability. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT'),
(41, 'Free CAT Mock Test 4', '2009-11-21 07:11:33', '1', 70, 70, 135, 0.25, '<ol><li>The total time for the test is 135 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Verbal Ability & Reading Comprehension, <b>Section II</b> - Quantitative Ability, and <b>Section III</b> - Data Interpretation & Logical Ability. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT'),
(42, 'Free CAT Mock Test 5', '2009-11-27 23:07:26', '1', 70, 70, 135, 0.25, '<ol><li>The total time for the test is 135 minutes.</li><li>This test is divided into three sections: <b>Section I</b> - Data Interpretation & Logical Ability, <b>Section II</b> - Quantitative Ability, and <b>Section III</b> - Verbal Ability & Reading Comprehension. All questions in the test carry equal marks.</li><li>You may work on any part of the test at any time during the test.</li><li>For each question, out of the suggested answers ONLY ONE is correct.</li><li>Mark your response to each question by selecting/clicking the radio button corresponding to the right answer.</li><li>Use of calculators, scales and other measuring instruments is not permitted.</li><li>You will be required to demonstrate adequate competence on each of the three parts.</li><li>Wrong answers carry negative marks. The negative marking scheme is 1/4 of the marks allotted to the question. Hence desist from guessing wildly.</li></ol>', 'FLT');
