package com.binaryedu.exceptions;

public enum BinaryExceptionCodes
{
	UNKNOWN_ERROR,
	USER_ALREADY_EXISTS,
	USER_DOES_NOT_EXIST,
	USER_NOT_ACTIVE,
	PASSWORD_INCORRECT,
	ACTIVATION_KEY_INCORRECT,
	UNABLE_TO_SEND_EMAIL,
	LINK_EXPIRED
}
